dj_reff/urls.py
from entries.views import landing_page, LandingPageView, SignupView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from entries.views import EntryDetailShortURLView, TestingView, EntryFillView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('testing/', TestingView.as_view(), name='testing'),
    # Change the URL .py folder from global to app-specific ('entries' in our case)
    path('entries/', include('entries.urls', namespace="entries")),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(next_page="landing-page"), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    # the following path needs to specify the uid in base64 and the token for a successful password reset
    path('password-confirm-done/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('fill-<str:short_url>/', EntryFillView.as_view(), name='entry-fill'),
    # the following path needs to stay last, otherwise the it would raise an error
    path('<str:short_url>/', EntryDetailShortURLView.as_view(),
         name='entry-detail-short-url'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

entries/urls.py
from django.contrib import admin
from django.urls import path
from entries.views import entry_list, entry_detail, entry_create, entry_update, entry_delete, review_create, EntryListView, EntryDetailView, EntryCreateView, EntryUpdateView, EntryDeleteView, MyEntryListView, EntryListByCategoryView, MyEntryListByCategoryView, ReviewCreateView, ReviewListView, RequestEntryCreateView, EntryFillView

app_name = "entries"

urlpatterns = [
    # By giving paths names, we can reference the paths across HTML files without worrying
    # about a ripple effect taking place when changing the path URL below.
    path('', EntryListView.as_view(), name='entry-list'),
    path('create/', EntryCreateView.as_view(), name='entry-create'),
    path('create-request/', RequestEntryCreateView.as_view(), name='entry-create-request'),
    # the path below has been implemented through the entry-list path using '?param=xXx' parameters instead
    # path('mine/', MyEntryListView.as_view(), name='my-entry-list'),
    # the '<>' syntax is used when generating dynamic URLs;
    # it is also recommended to keep the URL paths
    # containing primary keys (<pk>) at the bottom of the list;
    # or the primary key can be declared as <int: pk>
    path('<int:pk>/', EntryDetailView.as_view(), name='entry-detail'),
    path('update-<int:pk>/', EntryUpdateView.as_view(), name='entry-update'),
    # the path below has been added to the parent urls.py file;
    # path('fill-<str:short_url>/', EntryFillView.as_view(), name='entry-fill'),
    path('delete-<int:pk>/', EntryDeleteView.as_view(), name='entry-delete'),
    path('review-<int:pk>/', review_create, name='review-create'),
    path('reviews/', ReviewListView.as_view(), name='review-list'),
    # the paths below have been implemented through the entry-list path using '?param=xXx' parameters instead
    # path('category-<str:category>/', EntryListByCategoryView.as_view(), name='entry-list-by-category'),
    # path('mine/<str:category>/', MyEntryListByCategoryView.as_view(), name='my-entry-list-by-category')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
    <title>REFF</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <!-- <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet"> -->

    <link rel="shortcut icon" href="{% static 'images/favicon_48x48.ico' %}" />

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Cookie&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Epilogue:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Lobster&display=swap');
    </style>
        
</head>

<body class="font-epilogue">
    <div class="max-w-7xl mx-auto">
        {% include 'navbar.html' %}
        {% block content %}

        {% endblock content %}
    </div>
    {% include 'scripts.html' %}
</body>

</html>

templates/landing.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 mt-5 mx-auto">
    <div class="flex flex-col text-center w-full mb-10">
      <h2 class="text-xl text-blue-500 tracking-widest font-medium title-font mb-1">Making the web a more trustworthy
        place</h2>
      <h1 class="sm:text-3xl text-xl font-medium title-font text-gray-900">through peer-reviewed facts</h1>
    </div>
    <div class="flex flex-wrap -m-4">
      <div class="p-4 md:w-1/3">
        <div class="flex rounded-lg h-full bg-gray-100 p-8 flex-col">
          <div class="flex items-center mb-3">
            <div
              class="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-blue-500 text-white flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                class="w-5 h-5" viewBox="0 0 24 24">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path d="M4 20h4l10.5 -10.5a1.5 1.5 0 0 0 -4 -4l-10.5 10.5v4" />
                <line x1="13.5" y1="6.5" x2="17.5" y2="10.5" />
              </svg>
            </div>
            <h2 class="text-gray-900 text-2xl title-font font-medium">Make entry</h2>
          </div>
          <div class="flex-grow">
            <p class="leading-relaxed text-base">Become part of the community and start making entries today. Other
              users will peer-review them.</p>
            <a href="{% url 'entries:entry-create' %}" class="mt-3 text-blue-500 inline-flex items-center text-xl">Learn
              More
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      <div class="p-4 md:w-1/3">
        <div class="flex rounded-lg h-full bg-gray-100 p-8 flex-col">
          <div class="flex items-center mb-3">
            <div
              class="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-blue-500 text-white flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                class="w-5 h-5" viewBox="0 0 24 24">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <circle cx="10" cy="10" r="7" />
                <path d="M21 21l-6 -6" />
                <line x1="10" y1="13" x2="10" y2="13.01" />
                <path d="M10 10a1.5 1.5 0 1 0 -1.14 -2.474" />
              </svg>
            </div>
            <h2 class="text-gray-900 text-2xl title-font font-medium">Request entry</h2>
          </div>
          <div class="flex-grow">
            <p class="leading-relaxed text-base">Make an incomplete entry on someone's behalf and ask them to fill out
              the missing fields.</p>
            <a href="{% url 'entries:entry-create-request' %}"
              class="mt-3 text-blue-500 inline-flex items-center text-xl">Learn More
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      <div class="p-4 md:w-1/3">
        <div class="flex rounded-lg h-full bg-gray-100 p-8 flex-col">
          <div class="flex items-center mb-3">
            <div
              class="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-blue-500 text-white flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                class="w-5 h-5" viewBox="0 0 24 24">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <polyline points="12 4 4 8 12 12 20 8 12 4" />
                <polyline points="4 12 12 16 20 12" />
                <polyline points="4 16 12 20 20 16" />
              </svg>
            </div>
            <h2 class="text-gray-900 text-2xl title-font font-medium">Browse entries</h2>
          </div>
          <div class="flex-grow">
            <p class="leading-relaxed text-base">Curious to see what other facts have been posted to Reff?</p>
            <a href="{% url 'entries:entry-list' %}" class="mt-3 text-blue-500 inline-flex items-center text-xl">Learn
              More
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="flex flex-col text-center w-full mb-10 mt-10">
  <h2 class="text-xl text-blue-500 tracking-widest font-medium title-font mb-1">We sure do like some</h2>
  <h1 class="sm:text-3xl text-2xl font-medium title-font text-gray-900">stats</h1>
</div>

<section class="text-gray-600 body-font">
  <div class="container px-5 pt-0 mx-auto">

    <div class="flex flex-wrap -m-4 text-center mb-10">
      <div class="p-4 md:w-1/4 sm:w-1/2 w-full">
        <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            class="text-blue-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <polyline points="12 4 4 8 12 12 20 8 12 4" />
            <polyline points="4 12 12 16 20 12" />
            <polyline points="4 16 12 20 20 16" />
          </svg>
          <h2 class="title-font font-medium text-3xl text-gray-900">{{ num_entries }}</h2>
          <p class="leading-relaxed">Total entries</p>
        </div>
      </div>

      <div class="p-4 md:w-1/4 sm:w-1/2 w-full">
        <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            class="text-blue-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <path
              d="M7 11v8a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1v-7a1 1 0 0 1 1 -1h3a4 4 0 0 0 4 -4v-1a2 2 0 0 1 4 0v5h3a2 2 0 0 1 2 2l-1 5a2 3 0 0 1 -2 2h-7a3 3 0 0 1 -3 -3" />
          </svg>
          <h2 class="title-font font-medium text-3xl text-gray-900">{{ num_likes }}</h2>
          <p class="leading-relaxed">Liked entries</p>
        </div>
      </div>


      <div class="p-4 md:w-1/4 sm:w-1/2 w-full">
        <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            class="text-blue-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <path d="M20 17v-12c0 -1.121 -.879 -2 -2 -2s-2 .879 -2 2v12l2 2l2 -2z" />
            <path d="M16 7h4" />
            <path d="M18 19h-13a2 2 0 1 1 0 -4h4a2 2 0 1 0 0 -4h-3" />
          </svg>
          <h2 class="title-font font-medium text-3xl text-gray-900">{{ num_reviews }}</h2>
          <p class="leading-relaxed">Total reviews</p>
        </div>
      </div>

      <div class="p-4 md:w-1/4 sm:w-1/2 w-full">
        <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            class="text-blue-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
            <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"></path>
            <circle cx="9" cy="7" r="4"></circle>
            <path d="M23 21v-2a4 4 0 00-3-3.87m-4-12a4 4 0 010 7.75"></path>
          </svg>
          <h2 class="title-font font-medium text-3xl text-gray-900">{{ num_users }}</h2>
          <p class="leading-relaxed">Total users</p>
        </div>
      </div>

    </div>
  </div>
</section>


{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font font-semibold">
  <div class="max-w-7xl mx-auto">
    <header class="text-gray-600 body-font">
      <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center space-y-2">
        <a href="{% url 'landing-page' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">

          <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round"
            stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-blue-500 rounded-full"
            viewBox="0 0 24 24">
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <path d="M5.931 6.936l1.275 4.249m5.607 5.609l4.251 1.275" />
            <path d="M11.683 12.317l5.759 -5.759" />
            <circle cx="5.5" cy="5.5" r="1.5" />
            <circle cx="18.5" cy="5.5" r="1.5" />
            <circle cx="18.5" cy="18.5" r="1.5" />
            <circle cx="8.5" cy="15.5" r="4.5" />
          </svg>

          <span class="ml-3 text-4xl font-lobster">Reff</span>
        </a>
        <nav
          class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-row items-center text-base justify-center space-x-2">

          <!-- <a href="{% url 'entries:entry-list' %}" class="mr-5 hover:text-gray-900">Entries</a> -->

          <a href="{% url 'entries:entry-list' %}">
            <button type="button"
              class="focus:outline-none text-white text-base py-1.5 px-4 rounded-md bg-blue-500 hover:bg-blue-600 hover:shadow-lg flex items-center">
              <svg class="w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                stroke="currentColor" stroke-width="2">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <polyline points="12 4 4 8 12 12 20 8 12 4" />
                <polyline points="4 12 12 16 20 12" />
                <polyline points="4 16 12 20 20 16" />
              </svg>
              Entries
            </button>
          </a>

          {% if request.user.is_authenticated %}
          <!-- <a href="{% url 'entries:entry-list' %}?by_me=true" class="mr-5 hover:text-gray-900">My Entries</a> -->
          <!-- <a href="{% url 'entries:entry-list' %}?likes=true" class="mr-5 hover:text-gray-900">My Likes</a> -->

          <a href="{% url 'entries:entry-list' %}?likes=true">
            <button type="button"
              class="focus:outline-none text-white text-base py-1.5 px-4 rounded-md bg-blue-500 hover:bg-blue-600 hover:shadow-lg flex items-center">
              <svg class="w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                stroke="currentColor" stroke-width="2">
                <path
                  d="M16.5 3c-1.74 0-3.41.81-4.5 2.09C10.91 3.81 9.24 3 7.5 3 4.42 3 2 5.42 2 8.5c0 3.78 3.4 6.86 8.55 11.54L12 21.35l1.45-1.32C18.6 15.36 22 12.28 22 8.5 22 5.42 19.58 3 16.5 3zm-4.4 15.55l-.1.1-.1-.1C7.14 14.24 4 11.39 4 8.5 4 6.5 5.5 5 7.5 5c1.54 0 3.04.99 3.57 2.36h1.87C13.46 5.99 14.96 5 16.5 5c2 0 3.5 1.5 3.5 3.5 0 2.89-3.14 5.74-7.9 10.05z" />
              </svg>
              My likes
            </button>
          </a>


          {% endif %}

        </nav>

        <div class="flex md:flex-row flex-col md:pt-0 pt-2 justify-center sm:space-x-5">
          {% if not request.user.is_authenticated %}
          <div class="flex flex-wrap content-center">
            <a href="{% url 'signup' %}" class="hover:text-gray-900 mx-auto">Signup</a>
          </div>
          {% endif %}
          {% if request.user.is_authenticated %}
          <div>
            <a class="">
              <div class="rounded-full border-4 px-3 py-2 flex flex-row space-x-1 mx-auto">
                <div class="font-light"> Logged in as: </div>
                <div class="font-bold">{{ request.user.username }} </div>
              </div>
            </a>
          </div>
          <div class="flex flex-wrap content-center">
            <a href="{% url 'logout' %}"
              class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0 mx-auto">Logout
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
          {% else %}
          <div class="flex flex-wrap content-center">
            <a href="{% url 'login' %}"
              class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0 mx-auto">Login
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
          {% endif %}
        </div>

      </div>
    </header>
  </div>
  </div>
  </nav>
  </div>
</header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>

templates/second_page.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>Hello World</h1>
        <p>This is our second HTML page</p>
        <ul>
            {% for entry in entries %}
            <li> {{ entry }} </li>
            {% endfor %}
        </ul>
        <script src="" async defer></script>
    </body>
</html>