dj_reff/urls.py
from entries.views import landing_page, LandingPageView, SignupView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from entries.views import EntryDetailShortURLView, TestingView, EntryFillView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('testing/', TestingView.as_view(), name='testing'),
    # Change the URL .py folder from global to app-specific ('entries' in our case)
    path('entries/', include('entries.urls', namespace="entries")),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(next_page="landing-page"), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    # the following path needs to specify the uid in base64 and the token for a successful password reset
    path('password-confirm-done/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('fill-<str:short_url>/', EntryFillView.as_view(), name='entry-fill'),
    # the following path needs to stay last, otherwise the it would raise an error
    path('<str:short_url>/', EntryDetailShortURLView.as_view(),
         name='entry-detail-short-url'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

entries/urls.py
from django.contrib import admin
from django.urls import path
from entries.views import entry_list, entry_detail, entry_create, entry_update, entry_delete, review_create, EntryListView, EntryDetailView, EntryCreateView, EntryUpdateView, EntryDeleteView, MyEntryListView, EntryListByCategoryView, MyEntryListByCategoryView, ReviewCreateView, ReviewListView, RequestEntryCreateView, EntryFillView

app_name = "entries"

urlpatterns = [
    # By giving paths names, we can reference the paths across HTML files without worrying
    # about a ripple effect taking place when changing the path URL below.
    path('', EntryListView.as_view(), name='entry-list'),
    path('create/', EntryCreateView.as_view(), name='entry-create'),
    path('create-request/', RequestEntryCreateView.as_view(), name='entry-create-request'),
    # the path below has been implemented through the entry-list path using '?param=xXx' parameters instead
    # path('mine/', MyEntryListView.as_view(), name='my-entry-list'),
    # the '<>' syntax is used when generating dynamic URLs;
    # it is also recommended to keep the URL paths
    # containing primary keys (<pk>) at the bottom of the list;
    # or the primary key can be declared as <int: pk>
    path('<int:pk>/', EntryDetailView.as_view(), name='entry-detail'),
    path('update-<int:pk>/', EntryUpdateView.as_view(), name='entry-update'),
    # the path below has been added to the parent urls.py file;
    # path('fill-<str:short_url>/', EntryFillView.as_view(), name='entry-fill'),
    path('delete-<int:pk>/', EntryDeleteView.as_view(), name='entry-delete'),
    path('review-<int:pk>/', review_create, name='review-create'),
    path('reviews/', ReviewListView.as_view(), name='review-list'),
    # the paths below have been implemented through the entry-list path using '?param=xXx' parameters instead
    # path('category-<str:category>/', EntryListByCategoryView.as_view(), name='entry-list-by-category'),
    # path('mine/<str:category>/', MyEntryListByCategoryView.as_view(), name='my-entry-list-by-category')
]

entries/views.py
from django.core.mail import send_mail
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from entries.models import Entry, Review, User, Like
from entries.forms import EntryForm, EntryModelForm, CustomUserCreationForm, ReviewModelForm, RequestEntryModelForm, FillEntryModelForm
# folder contains TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views import generic
# we'll use this class to verify that the current user is authenticated
from django.contrib.auth.mixins import LoginRequiredMixin

# Use custom url_generator to assign to each new entry
from algorithms.random_url_string import url_generator

# Use domain_extractor to extract the domain from the long URL source
from algorithms.domain_extractor import url_parser

# We'll use these classes to paginate a higher number of entries that are to be displayed
from django.core.paginator import Paginator, EmptyPage

# we need to use Avg to calculate the average scores
from django.db.models import Avg

# use this method for passing the current date and time when filling a request-type entry
from datetime import datetime

# Used for searching the DB against multiple fields
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector

# Generally speaking, web pages follow the CRUD+L format: Create, Retrieve, Updated, Delete and List

# Class view


class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")

# Class view


class LandingPageView(generic.TemplateView):
    template_name = "landing.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # get all relevant data from DB to pass onto the context
        num_entries = Entry.objects.count()
        num_users = User.objects.count()
        num_reviews = Review.objects.count()
        num_likes = Like.objects.count()

        # add data to context
        context['num_entries'] = num_entries
        context['num_users'] = num_users
        context['num_reviews'] = num_reviews
        context['num_likes'] = num_likes

        print(context)
        return context

# Class view


class TestingView(generic.TemplateView):
    template_name = "entries/testing.html"


# Class view
# By also inheritting from LoginRequiredMixin, we restrict access to this particular view (it can only be called when the user is logged in)
class EntryListView(LoginRequiredMixin, generic.ListView):
    template_name = "entries/entry_list.html"
    # Declare the number of entries per page
    paginate_by = 10
    # # Order entries by date_created (the '-' means last added first)
    # queryset = Entry.objects.all().order_by('-date_created')

    def get_queryset(self):
        
        # if the search function is being used, further filter the queryset
        if 'search' in self.request.GET.keys():
            search_keyword = self.request.GET['search']
            # entries = entries.filter(fact__contains=search_keyword)
            # if the value of the parameter is longer than 0 characters, do the lookup
            if len(search_keyword) > 0:
                search_vector = SearchVector(
                    "fact", weight="A") + SearchVector("source", weight="A") + SearchVector("user__username", weight="A")
                search_query = SearchQuery(search_keyword, search_type='websearch')
                # returns all of the entries that contain all of the searched keywords (they don't have to be consecutive words in the entry)
                # so far the search takes into account the fact, the source and the user
                
                # first filter looks up all entries containing the relevant keywords (fact, source and username)
                entries = Entry.objects.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)).filter(search=search_query).order_by("-rank")
                # if no entries are returned, the second filter searches at substring level (fact, source and username)
                if (len(entries)==0):
                    entries = Entry.objects.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)).filter(search__icontains=search_keyword).order_by("-rank")
            # otherwise just return all entries        
            else:
                entries = Entry.objects.all().order_by('-date_created')
        # Order entries by date_created (the '-' means last added first)
        # return all entries if there is no search parameter in the URL
        else:    
            entries = Entry.objects.all().order_by('-date_created')
        
        
        if 'category' in self.request.GET.keys():
            category = self.request.GET['category']
            # if the category is different to 'all' apply another filter to the entries
            if (category != 'all'):
                entries = entries.filter(category=category)
        # Filter the queryset in order to display entries created by the user logged in
        if 'by_me' in self.request.GET.keys():
            by_me = self.request.GET['by_me']
            if by_me == 'true':
                entry_user = self.request.user
                entries = entries.filter(user=entry_user)
                # print(entries)

        if 'likes' in self.request.GET.keys():
            likes = self.request.GET['likes']
            if likes == 'true':
                entry_user = self.request.user
                # fetch all the likes of the currently logged in user
                likes = Like.objects.filter(user=entry_user)
                entry_id_list = list()
                # save the entry id's corresponding to each like in a list
                for like in likes:
                    entry_id_list.append(like.entry_id)
                # print(entry_id_list)
                # filter the entries to only contain the ones liked by the user
                entries = entries.filter(id__in=entry_id_list)
                # print(entries)

        # make sure only the full entries are included (not the request-type entries)
        entries = entries.filter(normal_entry=True)

        return entries

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # default value for category
        category = 'all'
        # grab the 'category' parameter from the URL of form "/?category=xXxX"
        if 'category' in self.request.GET.keys():
            category = self.request.GET['category']
        # add category to context
        context['category'] = category
        # add number of entries to context
        context["num_entries"] = len(self.get_queryset())
        # print(self.request.GET)
        # print('LENGTH ' + str(len(self.get_queryset())))
        # default value for parameter 'by_me' is 'false'
        by_me = 'false'
        if 'by_me' in self.request.GET.keys() and self.request.GET['by_me'] == 'true':
            by_me = 'true'
        context['by_me'] = by_me

        # default value for parameter 'likes' is 'false'
        likes = 'false'
        if 'likes' in self.request.GET.keys() and self.request.GET['likes'] == 'true':
            likes = 'true'
        context['likes'] = likes

        additional_info = {}

        # add an 'additional_info' dictionary to the context in which we will store the domain urls to display in the template
        object_list = context['object_list']
        for object in object_list:
            domain_url = url_parser(object.source)
            additional_info[object.id] = domain_url

        context['additional_info'] = additional_info

        # add an 'additional_info_2' dictionary to the context in which we will store the average scores for each entry we iterate over in the template
        additional_info_2 = {}
        for object in object_list:
            # returns a dictionary with the key 'rating__avg'
            score = Review.objects.filter(
                entry=object).aggregate(Avg('rating'))
            # returns the actual average score value
            average_score = score['rating__avg']
            # print(average_score)

            # round all float instances to 1 decimal, and replace all NoneType with 0
            if isinstance(average_score, float):
                average_score = round(average_score, 1)
                # print(average_score)
            else:
                average_score = 0
            additional_info_2[object.id] = average_score

        context['additional_info_2'] = additional_info_2

        # print('CONTEXT --->', context)
        print()

        return context


# Class view
class ReviewListView(LoginRequiredMixin, generic.ListView):
    template_name = "entries/review_list.html"
    # Declare the number of entries per page
    paginate_by = 10

    def get_queryset(self):
        # Get the entry id of the entry we want to see the reviews for
        entry_id = self.request.GET['id']

        # check to see if there is a 'search' parameter in the URL
        if 'search' in self.request.GET.keys():
            # fetch all reviews for that specific entry_id which contain the search parameter
            # reviews = Review.objects.filter(entry_id=entry_id)
            # search_keyword = self.request.GET['search']
            # reviews = reviews.filter(comment__contains=search_keyword)
            
            search_keyword = self.request.GET['search']
            # if the search parameter contains a value, do the lookup
            if len(search_keyword) > 0: 
                search_vector = SearchVector("comment", weight="A") + SearchVector("rating", weight="A") + SearchVector("user__username", weight="A")
                search_query = SearchQuery(search_keyword, search_type='websearch')
            

entries/templates/entries/entry_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<h1 class="text-4xl text-gray-800 m-5 md:max-w-lg md:mx-auto">New entry</h1>
<div class="md:max-w-lg md:mx-auto m-5">
    <!-- 'action="."' below indicated where the form is submitted. '.' means current URL -->
    <form method="POST" action=".">
        <!-- The csrf token below is good security implementation for form submission within Django -->
        {% csrf_token %}
        {{ form|crispy }}

        <!-- The styling below is to remove the asterisk from the mandatory fields -->
        <style>
            .asteriskField {
                display: none;
            }
        </style>
        <button class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white" type="submit"> Submit
        </button>
    </form>
    <div class='mt-5 mb-10 border-t border-gray-500 pt-2'><a class="hover:text-blue-500 mt-3 text-xl"
            href="{% url 'entries:entry-list' %}">Back to entry list</a></div>
</div>

{% endblock content %}

entries/templates/entries/entry_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<hr />
<div class="max-w-lg mx-auto mt-10">
    {% if are_users_the_same == True %}
    <h1 class="text-xl text-gray-800">Are you sure you want to delete the entry?</h1>
    <!-- 'action="."' below indicated where the form is submitted. '.' means current URL -->
    <form method="POST" action=".">
        <!-- The csrf token below is good security implementation for form submission within Django -->
        {% csrf_token %}
        {{ form|crispy }}

        <button class="bg-red-500 hover:bg-red-600 px-3 py-2 rounded-md text-white mt-5 font-bold" type="submit"> Delete </button>
    </form>
    {% else %}
    <div class="flex flex-col md:pr-10 md:mb-0 mb-6 pr-0 w-full md:w-auto md:text-left text-center">
        <h2 class="text-xs text-indigo-500 tracking-widest font-medium title-font mb-1">ACCESS DENIED
        </h2>
        <h1 class="md:text-3xl text-2xl font-medium title-font text-gray-900">You are not the original
            creator
        </h1>
    </div>
    {% endif %}
    <div class='mt-5 mb-10 border-t border-gray-500 pt-2'><a class="hover:text-blue-500 mt-3 text-xl" href="{% url 'entries:entry-list' %}">Back to entry list</a></div>
</div>
{% endblock content %}

entries/templates/entries/entry_detail.html
{% extends "base.html" %}


{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-5 mx-auto">
    <div class="lg:w-8/12 mx-auto flex flex-wrap">
      <div class="lg:w-4/5">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Category</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ entry.category }}</h1>
        <div class="flex mb-4">
          <a class="flex-grow text-blue-500 border-b-2 border-blue-500 py-2 text-lg px-1 font-semibold">Fact</a>
          <a href="{% url 'entries:review-create' entry.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 hover:bg-gray-100">Review</a>
          <a href="{% url 'entries:entry-update' entry.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 hover:bg-gray-100">Update</a>
        </div>
        <p class="leading-relaxed mb-4 font-jet_brains_mono break-words">{{ entry.fact }}</p>
        <div class="flex border-t border-gray-200 py-2">

          <span class="text-blue-500">Source</span>
          <span class="ml-auto mr-2 text-gray-900 font-semibold text-blue-500 hover:text-blue-800 break-all pl-2 sm:pl-0"><a
              href="{{ entry.source }}">{{ source_domain }}</a></span>

          <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000">
            <path d="M0 0h24v24H0V0z" fill="none" />
            <path
              d="M17 7h-4v2h4c1.65 0 3 1.35 3 3s-1.35 3-3 3h-4v2h4c2.76 0 5-2.24 5-5s-2.24-5-5-5zm-6 8H7c-1.65 0-3-1.35-3-3s1.35-3 3-3h4V7H7c-2.76 0-5 2.24-5 5s2.24 5 5 5h4v-2zm-3-4h8v2H8z" />
          </svg>
        </div>

        <div class="flex border-t border-gray-200 py-2">

          <span class="text-gray-500">Created by</span>
          <span class="ml-auto mr-2 text-gray-900">{{ entry.user }}</span>

          <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000">
            <path d="M0 0h24v24H0V0z" fill="none" />
            <path
              d="M10.25 13c0 .69-.56 1.25-1.25 1.25S7.75 13.69 7.75 13s.56-1.25 1.25-1.25 1.25.56 1.25 1.25zM15 11.75c-.69 0-1.25.56-1.25 1.25s.56 1.25 1.25 1.25 1.25-.56 1.25-1.25-.56-1.25-1.25-1.25zm7 .25c0 5.52-4.48 10-10 10S2 17.52 2 12 6.48 2 12 2s10 4.48 10 10zM10.66 4.12C12.06 6.44 14.6 8 17.5 8c.46 0 .91-.05 1.34-.12C17.44 5.56 14.9 4 12 4c-.46 0-.91.05-1.34.12zM4.42 9.47c1.71-.97 3.03-2.55 3.66-4.44C6.37 6 5.05 7.58 4.42 9.47zM20 12c0-.78-.12-1.53-.33-2.24-.7.15-1.42.24-2.17.24-3.13 0-5.92-1.44-7.76-3.69C8.69 8.87 6.6 10.88 4 11.86c.01.04 0 .09 0 .14 0 4.41 3.59 8 8 8s8-3.59 8-8z" />
          </svg>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Date created</span>
          <span class="ml-auto mr-2 text-gray-900">{{ entry.date_created | date:"d F Y" }}</span>

          <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24px" viewBox="0 0 24 24"
            width="24px" fill="#000000">
            <rect fill="none" height="24" width="24" />
            <path
              d="M5,10h14v2h2V6c0-1.1-0.9-2-2-2h-1V2h-2v2H8V2H6v2H5C3.89,4,3.01,4.9,3.01,6L3,20c0,1.1,0.89,2,2,2h7v-2H5V10z M5,6h14v2H5 V6z M22.84,16.28l-0.71,0.71l-2.12-2.12l0.71-0.71c0.39-0.39,1.02-0.39,1.41,0l0.71,0.71C23.23,15.26,23.23,15.89,22.84,16.28z M19.3,15.58l2.12,2.12l-5.3,5.3H14v-2.12L19.3,15.58z" />
          </svg>

        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Reviewed by</span>
          <span class="ml-auto mr-2 text-gray-900">{{ reviews_number }} user(s)</span>

          <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24px" viewBox="0 0 24 24"
            width="24px" fill="#000000">
            <g>
              <rect fill="none" height="24" width="24" />
            </g>
            <g>
              <g />
              <g>
                <path d="M16.67,13.13C18.04,14.06,19,15.32,19,17v3h4v-3C23,14.82,19.43,13.53,16.67,13.13z" />
                <path
                  d="M15,12c2.21,0,4-1.79,4-4c0-2.21-1.79-4-4-4c-0.47,0-0.91,0.1-1.33,0.24C14.5,5.27,15,6.58,15,8s-0.5,2.73-1.33,3.76 C14.09,11.9,14.53,12,15,12z" />
                <path
                  d="M9,12c2.21,0,4-1.79,4-4c0-2.21-1.79-4-4-4S5,5.79,5,8C5,10.21,6.79,12,9,12z M9,6c1.1,0,2,0.9,2,2c0,1.1-0.9,2-2,2 S7,9.1,7,8C7,6.9,7.9,6,9,6z" />
                <path
                  d="M9,13c-2.67,0-8,1.34-8,4v3h16v-3C17,14.34,11.67,13,9,13z M15,18H3l0-0.99C3.2,16.29,6.3,15,9,15s5.8,1.29,6,2V18z" />
              </g>
            </g>
          </svg>

        </div>
        <div class="flex">
          <span class="title-font font-medium text-lg sm:text-2xl text-gray-900">Score: {{ average_score }}</span>
          <a class="flex ml-auto text-white bg-blue-500 border-0 px-3 sm:py-2 sm:px-6 focus:outline-none hover:bg-blue-600 rounded"
            href="{% url 'entries:review-list' %}?id={{ entry.id }}">
            <button class="font-semibold">See
              reviews</button> </a>
          {% if already_liked == 'no' %}
          <form action="{% url 'entry-detail-short-url' short_url=entry.short_url %}">
            <input type="hidden" name="like" value="yes">
            <button type="submit"
              class="rounded-full w-10 h-10 bg-gray-200 hover:bg-gray-300 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" class="w-5 h-5" stroke="grey" stroke-opacity="1" fill-opacity="0.3"
                viewBox="0 0 24 24">
                <path
                  d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z">
                </path>
              </svg>
            </button>
          </form>
          {% else %}
          <form action="{% url 'entry-detail-short-url' short_url=entry.short_url %}">
            <input type="hidden" name="like" value="no">
            <button type="submit"
              class="rounded-full w-10 h-10 bg-pink-400 hover:bg-pink-600 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg fill="purple" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" stroke-opacity="0.5"
                viewBox="0 0 24 24">
                <path
                  d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z">
                </path>
              </svg>
            </button>
          </form>
          {% endif %}


          <button onclick="copyToClipboard()"
            class="rounded-full w-10 h-10 bg-gray-200 hover:bg-gray-300 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="grey" fill-opacity="0.2" stroke="grey" stroke-linecap="round" stroke-width="3" stroke-linejoin="round" stroke-width="2" class="w-5 h-5"
              viewBox="0 0 24 24">
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <path d="M9 5h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-12a2 2 0 0 0 -2 -2h-2" />
              <rect x="9" y="3" width="6" height="4" rx="2" />
            </svg>
          </button>


          <script>
            function copyToClipboard(text) {
              var inputc = document.body.appendChild(document.createElement("input"));
              inputc.value = window.location.href;
              inputc.focus();
              inputc.select();
              document.execCommand('copy');
              inputc.parentNode.removeChild(inputc);
              alert("URL Copied.");
            }
          </script>
        </div>
        <h1 class="border-t mt-5 mb-5 pt-2 text-right">Note: the share-able URL contains no capital letters.</h1>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

entries/templates/entries/entry_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-5 mx-auto">
        <div class="lg:w-8/12 mx-auto flex flex-wrap">
            <div class="lg:w-4/5">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">Category</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ entry.category }}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'entry-detail-short-url' entry.short_url %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 hover:bg-gray-100">Fact</a>
                    <a href="{% url 'entries:review-create' entry.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 hover:bg-gray-100">Review</a>
                    <a href="{% url 'entries:entry-update' entry.pk %}"
                        class="flex-grow text-blue-500 border-b-2 border-blue-500 py-2 text-lg px-1 font-semibold">Update</a>
                </div>
                {% if are_users_the_same == True %}
                {% if entry_reviews_number == 0 %}
                <form method="POST">
                    <!-- The csrf token below is good security implementation for form submission within Django -->
                    {% csrf_token %}
                    {{ form|crispy }}

                    <!-- The styling below is to remove the asterisk from the mandatory fields -->
                    <style>
                        .asteriskField {
                            display: none;
                        }
                    </style>

                    <div class='flex-row'>
                        <button
                            class="text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded font-bold">Submit</button>
                        <a class="w-full bg-red-500 hover:bg-red-700 px-3 py-3 rounded-md text-white font-bold"
                            href="{% url 'entries:entry-delete' entry.pk %}">Delete</a>
                    </div>
                    {% else %}
                    <div class="flex flex-col md:pr-10 md:mb-0 mb-6 pr-0 w-full md:w-auto md:text-left text-center">
                        <h2 class="text-xs text-indigo-500 tracking-widest font-medium title-font mb-1">LIMITED OPTIONS
                        </h2>
                        <h1 class="md:text-3xl text-2xl font-medium title-font text-gray-900">The reviewing process has
                            started
                        </h1>
                        <div class='flex-row py-4'>
                            <a class="w-full bg-red-500 hover:bg-red-700 px-3 py-3 rounded-md text-white font-bold"
                                href="{% url 'entries:entry-delete' entry.pk %}">Delete</a>
                        </div>
                    </div>
                    {% endif %}
                    {% else %}
                    <div class="flex flex-col md:pr-10 md:mb-0 mb-6 pr-0 w-full md:w-auto md:text-left text-center">
                        <h2 class="text-xs text-indigo-500 tracking-widest font-medium title-font mb-1">ACCESS DENIED
                        </h2>
                        <h1 class="md:text-3xl text-2xl font-medium title-font text-gray-900">You are not the original
                            creator
                        </h1>
                    </div>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

entries/templates/entries/request_entry_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<h1 class="text-4xl text-gray-800 m-5 md:max-w-lg md:mx-auto">New request-type entry</h1>
<div class="md:max-w-lg md:mx-auto m-5">
    <!-- 'action="."' below indicated where the form is submitted. '.' means current URL -->
    <form method="POST" action=".">
        <!-- The csrf token below is good security implementation for form submission within Django -->
        {% csrf_token %}
        {{ form|crispy }}

        <!-- The styling below is to remove the asterisk from the mandatory fields -->
        <style>
            .asteriskField {
                display: none;
            }
        </style>

        <button class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white" type="submit"> Submit
        </button>
    </form>
    <div class='mt-5 mb-10 border-t border-gray-500 pt-2'><a class="hover:text-blue-500 mt-3 text-xl" href="{% url 'entries:entry-list' %}">Back to entry list</a></div>
</div>

{% endblock content %}